# deploy

name: Mock Deploy

on:
  push:
    branches: [ $default-branch ]
                                   # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
