# deploy

name: Mock Deploy

on:
  push:
    branches: [ $default-branch ]
                                   # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # does this work without?
          bundle
